// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceTeamApplicationTracker.Data;

namespace ServiceTeamApplicationTracker.Migrations
{
    [DbContext(typeof(ServiceTeamApplicationTrackerContext))]
    [Migration("20200924131108_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ServiceTeamApplicationTracker.Models.Tickets_Tracking", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AgentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Application")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ClosedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("External_Ticket_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncidentOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Last_UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OpenDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Point_of_Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resolution_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resolution_SubType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resolution_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ticket_Cat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ticket_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Work_Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
